<?php if (!defined('FARI')) die(); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Content-Language" content="en" />
    <meta name="description" content="Clubhouse" />
    <title>Clubhouse<?php if (!empty($room['name'])) echo ": {$room['name']}"; ?></title>

    <link rel="stylesheet" type="text/css" media="screen" href="<?php url('/public/css/reset.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php url('/public/css/codebase.css'); ?>" />

    <script src="<?php url('/public/javascript/prototype.js'); ?>" language="javascript" type="text/javascript"></script>
    <script src="<?php url('/public/javascript/scriptaculous/scriptaculous.js'); ?>" language="javascript" type="text/javascript"></script>
    <script src="<?php url('/public/javascript/clubhouse.js'); ?>" language="javascript" type="text/javascript"></script>

    <link rel="shortcut icon" type="image/x-icon" href="<?php url('/public/favicon.ico'); ?>" />
</head>
<?php echo $template; ?>
</html>