<?php if (!defined('FARI')) die(); ?>
<body>
    <div id="modal">
        <?php imageTag('images/clubhouse-small-header-logo.png'); ?>
        <h1>Sorry, this invitation has expired or the address is incorrect</h1>
        <p>Invitations expire after a certain amount of time for security reasons. Please write the person who invited
            you and ask them to send the invitation again.<br />We're sorry for the trouble.</p>
        <hr>
        <p>
            <a href="javascript:history.go(-1)">Go back a page</a>
        </p>
    </div>
</body>