<?php if (!defined('FARI')) die(); ?>
<body>
    <!-- main center block -->
    <div id="center" style="width:420px;">
        <div id="wrapper">
            <h1>Please enter your full name</h1>
            <div id="main">
                <form class="form" method="POST" action="<?php url('/guest/new/'); ?>">
                    <div class="field">
                        <label></label>
                        <input name="name" type="text" />
                        <span>This is the name other people will see in the chat room.</span>
                    </div>
                    <input name="code" type="hidden" value="<?php echo $code; ?>" />
                    <input type="submit" class="button" value="Sign in" />
                </form>
            </div>
        </div>
        <div class="bottom">&nbsp;</div>
    </div>
</body>