<?php if (!defined('FARI')) die(); ?>
<body>
    <div id="modal">
        <?php imageTag('images/clubhouse-small-header-logo.png'); ?>
        <h1>You need to change a setting in your web browser</h1>
        <p>Clubhouse requires a browser feature called JavaScript. All modern browsers support JavaScript. You probably
            just need to change a setting in order to turn it on.</p>
        <p>Please see: <a href="http://www.google.com/support/bin/answer.py?answer=23852">How to enable JavaScript
                in your browser</a>.<br />Thank you.</p>
        <hr>
        <p>
            <a href="javascript:history.go(-1)">Go back a page</a>
        </p>
    </div>
</body>