<?php if (!defined('FARI')) die(); ?>
<?php renderPartial('body'); ?> 
    <!-- header -->
    <div id="products"><a class="active" href="#">Clubhouse</a></div>
    
    <!-- menu -->
    <div id="menu">
        <ul>
            <li><a href="<?php url('/'); ?>">Lobby</a></li>
            <?php foreach($tabs as $roomName => $roomId): ?>
                <li class="<?php if ($room['id'] == $roomId) echo 'active'; ?>">
                    <a href="<?php url('/room/' . $roomId . '/'); ?>"><?php echo $roomName; ?></a>
                </li>
            <?php endforeach; ?>
            <li class="indent"><a href="<?php url('/transcripts/'); ?>">Files, Transcripts &amp; Search</a></li>
            
            <li class="right nobg"><a href="<?php url('/logout/'); ?>">Sign out</a></li>
            <?php if ($isAdmin): ?>
                <li class="right"><a href="<?php url('/settings/'); ?>">Settings</a></li>
                <li class="right"><a href="<?php url('/users/'); ?>">Users</a></li>
            <?php endif; ?>
        </ul>
    </div>

    <!-- left column -->
    <div id="left">
        <!-- messages -->
        <div id="main">
            <div id="ajax"></div>
            
            <?php if ($history): ?>
                <p id="history">See transcript for earlier messages</p>
            <?php endif; ?>

            <table id="result">
                <?php
                $lastUserName = '';
                $lastMessageType = '';

                foreach ($messages as $message):
                    if ($message['user'] == $lastUserName && $message['type'] == $lastMessageType) $lastUserName = '';
                    else $lastUserName = $message['user'];
                    $lastMessageType = $message['type'];

                    $ourMessage = '';
                    if ($message['type'] == 'text' && $message['userId'] == $userId) $ourMessage = ' our';
              ?>
                    <tr>
                        <td class="user <?php echo $message['type'] . $ourMessage; ?>"><?php echo $lastUserName; ?></td>
                        <td class="body <?php echo $message['type'] . $ourMessage; ?>">
                            <?php echo html_entity_decode($message['text']); if ($message['type'] == 'text'): ?>
                                <div id="highlight_<?php echo $message['id']; ?>"
                                     onclick="highlightMessage('<?php echo $message['id']; ?>');return false;"
                                     class="highlight<?php if ($message['highlight'] == 1) echo ' on'; ?>">
                                    <a href=""></a>
                                </div>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php
                $lastMessage = $message['id'];
                $lastUserName = $message['user'];

                endforeach;
              ?>
            </table>
            <script type="text/javascript">
                var userId = <?php echo $userId; ?>;
                var lastUserName = '<?php echo $lastUserName; ?>';
                var shortName = '<?php echo $shortName; ?>';
                var lastMessage = <?php echo (isset($lastMessage)) ? $lastMessage : 0; ?>;
                var lastMessageType = '<?php echo $lastMessageType; ?>';
            </script>
        </div>
        
        <div class="bottom">&nbsp;</div>
    </div>

    <!-- right column -->
    <div id="right">
        <!-- sound -->
        <div id="sound">
            <a href="<?php url('/javascript/'); ?>" onclick="soundSwitch('<?php url('public/images/') ?>');return false;">
                <input id="incomingSound" type="hidden" value="<?php url('public/audio/incoming.mp3'); ?>" />
                <img id="speaker" src="<?php url('public/images/sound-on.gif') ?>" alt="sound" />
            </a>
        </div>

        <!-- room, topic -->
        <h1 id="roomName"><?php echo $room['name']; ?></h1>

        <div id="description">
            <a id="addTopic" class="orange" onclick="editTopicToggle();return false;"
               href="<?php url('/javascript/'); ?>"></a>
            <span id="roomDescription" class="sub"><?php echo $room['description']; ?></span>
            <a id="topicEdit" class="gray" onclick="editTopicToggle();return false;" href="<?php url('/javascript/'); ?>"></a>
        </div>
        <form id="editTopicForm" style="display:none;" method="POST" action="<?php url('/room/topic/' . $room['id']); ?>">
            <textarea id="topicEntry" name="topic"></textarea>
            <input onclick="editTopic();return false;" type="submit" value="Save" />
            <span>or</span>
            <a class="orange" onclick="editTopicToggle();return false;" href="<?php url('/javascript/'); ?>">Cancel</a>
            <div id="dots" class='dots' style="display:none;">&nbsp;</div>
        </form>

        <form id="searchForm" class="form" method="POST" action="<?php url('/search/'); ?>">
            <input type="text" id="q" name="q" />
            <input type="submit" value="Search" />
        </form>

        <!-- room lock message -->
        <?php if ($room['locked'] != '0'): ?>
            <script type="text/javascript">var lockedRoom = true;</script>
            <p id="lockMessage">
                <strong>This room is locked &amp; off the record.</strong> No one else can enter this room. Any conversations
                or files will not be logged to the transcript.
            </p>
        <?php else: ?>
            <script type="text/javascript">var lockedRoom = false;</script>
            <p id="lockMessage" style="display:none;">
                <strong>This room is locked &amp; off the record.</strong> No one else can enter this room. Any conversations
                or files will not be logged to the transcript.
            </p>
        <?php endif; ?>

        <!-- participants -->
        <h2>Who's here?
            <a class="blue" href="<?php url('/room/leave/' . $room['id'] . '/'); ?>">Leave</a> <span>|</span>
            <span id="lockSpinner" style="display:none;" class='dots'>&nbsp;</span>
            <a class="blue" onclick="lockRoom('<?php url('/room/lock/' . $room['id']); ?>');return false;"
               id="lockLink" href="<?php url('/javascript/'); ?>">
                <?php echo ($room['locked'] != '0') ? 'Unlock' : 'Lock'; ?> room
            </a></h2>
        <ul id="participants"><li></li></ul>

        <!-- guest access -->
        <?php if ($room['guest'] != '0'): ?>
            <script type="text/javascript">
                var guestStatus = 'on';
           </script>
            
            <div id="guest" class="guest">
                <h2>
                    Guest access is <em id="guestStatus">on</em>
                    <span id="guestSpinner" style="display:none;" class='dots'>&nbsp;</span>
                    <a class="blue" onclick="guestRoom('<?php url('/room/guest/' . $room['id']); ?>');return false;"
                       href="<?php url('/javascript/'); ?>" id="guestLink">Turn it off</a>
                </h2>
                <h3 id="guestAddress" class="guest"><?php echo url('g/' . $room['guest'], TRUE, TRUE); ?></h3>
                <p id="guestNote">Anyone visiting the URL above will be able to participate in this chat room.</p>
            </div>
        <?php else: ?>
            <script type="text/javascript">
                var guestStatus = 'off';
           </script>

            <div id="guest" class="">
                <h2>
                    Guest access is <em id="guestStatus">off</em>
                    <span id="guestSpinner" style="display:none;" class='dots'>&nbsp;</span>
                    <a class="blue" onclick="guestRoom('<?php url('/room/guest/' . $room['id']); ?>');return false;"
                       href="<?php url('/javascript/'); ?>" id="guestLink">Turn it on</a>
                </h2>
                <h3 id="guestAddress" class="guest"></h3>
                <p id="guestNote" style="display:none;">Anyone visiting the URL above will be able to participate in this
                    chat room.</p>
            </div>
        <?php endif; ?>

        <!-- file upload -->
        <h2>Files
            <a class="blue" onclick="slideInOut('fileUpload');return false;" href="<?php url('/javascript/'); ?>
               "style="float:right;" href="">Upload a file</a></h2>
        <form id="fileUpload" action="<?php url('/file/upload/'); ?>" style="display:none;"
              enctype="multipart/form-data" method="POST" target="target">
            <p>Choose a file less than 10MB in size.</p>
            <input type="file" name="upload" id="upload" /><br />
            <input type="hidden" name="roomId" value="<?php echo $room['id']; ?>" />
            <input type="submit" value="Upload" onclick="fileUpload();" /> <span>or</span>
            <a onclick="slideInOut('fileUpload');return false;" href="<?php url('/javascript/'); ?>" class="orange">Cancel</a>
            <iframe id="target" name="target" src="#"></iframe>
        </form>
        <div id="fileUploadSpinner" style="display:none;">
            <img src="<?php url('/public/images/progress_bar.gif'); ?>" />
            <p id="fileUploadText"></p>
        </div>
        <ul id="fileListing"></ul>
    </div>

    <!-- footer -->
    <div id="footer">
        <form id="sendMessageForm" method="POST" action="<?php url('/message/speak/' . $room['id']); ?>">
            <textarea id="text" name="text"></textarea>
            <input onclick="sendMessage();return false;" type="submit" value="Send message" />
        </form>
    </div>

</body>