<?php if (!defined('FARI')) die(); ?>
<body>
    <div id="modal">
        <?php imageTag('images/clubhouse-small-header-logo.png'); ?>
        <h1>Sorry, but the specified user either doesn't exist or is inactive</h1>
        <p><strong>Did you type the URL?</strong><br />
        You may have typed the address (URL) incorrectly. Check to make sure you've got the exact right spelling,
        capitalization, etc.</p>
        <hr>
        <p>
            <a href="javascript:history.go(-1)">Go back a page</a>
        </p>
    </div>
</body>