<?php if (!defined('FARI')) die(); ?>
<body>
    <!-- main center block -->
    <div id="center">
        <div id="wrapper">
            <h1>Sign-in to your Clubhouse account.</h1>
            <div id="main">
                <?php foreach (flash() as $message): ?>
                    <div id="flash" style="margin-top:10px;" class="<?php echo $message['key']; ?>">
                        <?php echo $message['text']; ?>
                    </div>
                <?php endforeach; ?>
                <?php renderPartial('form'); ?>
            </div>
        </div>
        <div class="bottom">&nbsp;</div>
    </div>
</body>